spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/wiki_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:wiki_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:wiki_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
