spring.application.name=thymeleaf

# Datasource (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wiki_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:wiki_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:wiki_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# SQL init
spring.sql.init.mode=always
